version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    external: true